import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "@chatty/providers";
import { PropsWithChildren } from "react";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app"
};

export default function RootLayout({ children }: Readonly<PropsWithChildren>) {
    return (
        <html lang='en' suppressHydrationWarning>
            <body>
                <Providers>{children}</Providers>
            </body>
        </html>
    );
}
